window.FIREBASE_CONFIG = {
  apiKey: "PASTE_FROM_FIREBASE_CONSOLE",
  authDomain: "PASTE_FROM_FIREBASE_CONSOLE",
  databaseURL: "PASTE_FROM_FIREBASE_CONSOLE",
  projectId: "PASTE_FROM_FIREBASE_CONSOLE",
  storageBucket: "PASTE_FROM_FIREBASE_CONSOLE",
  messagingSenderId: "PASTE_FROM_FIREBASE_CONSOLE",
  appId: "PASTE_FROM_FIREBASE_CONSOLE"
};
